# --------
# @file     agent.py
# @author   Taylor Martin
# @date     May 2023
# @class    CS 470 Artificial Intelligence
#
# @brief    This file contains the agent class. For traversing the map generated by the environment class. Utilizes various AI pathfinding algorithms for traversal.
# --------------------

from environment import Environment
import copy # for deepcopy -> cpy_list = copy.deepcopy(org_list)

class Agent:
    
    """
    Agent Class 
    """

    def __init__(self, env):
        """
        Constructor
        """
        self.env = env
        self.path = []
        self.path_cost = 0
        self.path_length = 0
        self.explored = []
        self.frontier = []

    def breadth_first_search(self):
        """
        Breadth First Search
        """

    def lowest_cost_search(self):
        """
        Lowest Cost Search
        """
    def greedy_best_first_search(self):

        """
        Greedy Best First Search
        """
    
    def a_star_search(self):
        """
        A* Search
        """
    

    # After a successful search the program should do the following:

    # Draw the path on the map.
    # Denote all of the explored squares on the map.
    # Denote the current open/frige list.
    # Report the length of the path found.
    # Report the cost of the path found.
    # This does not require a graphical output (although that's probably best). You could draw a text version of the map (as in the sample file) and underline explored squares, bold open squares, and highlight squares on the successful path.
    # Algorithms: You will need to test the following algorithms:

    # Breadth first.
    # Lowest cost.
    # Greedy best first
    # A* with at least two different heuristics.
    # Experiments: For each algorithm you will need to do the following:

    # Show that the algorithm works. In particular you should show, with an actual figure, both the cells explored by the algorithm and the route that the algorithm finds. Make sure that the figure clearly shows that the algorithm works. For example, if there is a mountain range that impedes movement show that the algorithm searches for paths around it.